### ISSUE TITLE
[windows setup] dac_play install location is wrong when bitshares is installed

### ISSUE THREAD

**Issue by bitsha256** [bitsuperlab/bitshares_play#109]
This issue happens only when bitshares is installed.

**Comment by clar** [comment]
we need to use different GUID for play.

https://github.com/dacsunlimited/dac_play/blob/master/CMakeLists.txt#L19

**Comment by HackFisher** [comment]
@clar is that the reason?

**Comment by clar** [comment]
@HackFisher , yes , need to merge to dacplay

**Comment by clar** [comment]
fixed in https://github.com/bitsuperlab/bitshares_play/commit/c725d5b461d4e936922695f137c0686043ae8ff4
