### ISSUE TITLE
sub-module leveldb refer to an invalid reference

### ISSUE THREAD

**Issue by crazybits** [bitsuperlab/bitshares_play#129]
git submodule update --init --recursive
fatal: reference is not a tree: 028f9409247be6d3d09a157e8eb347a173afc599
Unable to checkout '028f9409247be6d3d09a157e8eb347a173afc599' in submodule path 'libraries/leveldb'

**Comment by HackFisher** [comment]
Refer this commit:

https://github.com/bitsuperlab/bitshares_play/commit/40fa9c8641c7314775f9552c7d3405443645d617
