### ISSUE TITLE
Unable to build on Ubuntu 

### ISSUE THREAD

**Issue by svk31** [bitsuperlab/bitshares_play#132]
I've been unable to build the releases from https://github.com/dacsunlimited/dac_play/releases since v0.0.3 due to a change in leveldb I believe, a fix would be great.

```
git submodule update --init --recursive
.....
Unable to checkout '028f9409247be6d3d09a157e8eb347a173afc599' in submodule path 'libraries/leveldb'
```

**Comment by bitsha256** [comment]
https://github.com/dacsunlimited/dac_play/commit/23607f2aefedc91397fdebc5519298fb7ece8f99

This commit fixed it.
