### ISSUE TITLE
ld: library not found for -ltcmalloc

### ISSUE THREAD

**Issue by koocaalijian** [bitsuperlab/bitshares_play#38]
Scanning dependencies of target bitcoin
[ 75%] Building CXX object libraries/bitcoin/CMakeFiles/bitcoin.dir/electrum.cpp.o
Linking CXX static library libbitcoin.a
[ 75%] Built target bitcoin
Linking CXX static library libbts_keyhotee.a
[ 75%] Built target bts_keyhotee
Linking C static library libminiupnpc.a
[ 79%] Built target upnpc-static
Scanning dependencies of target bts_api_generator
[ 79%] Building CXX object libraries/api/CMakeFiles/bts_api_generator.dir/bts_api_generator.cpp.o
Linking CXX executable bts_api_generator
ld: library not found for -ltcmalloc
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libraries/api/bts_api_generator] Error 1
make[1]: *** [libraries/api/CMakeFiles/bts_api_generator.dir/all] Error 2
make: *** [all] Error 2

**Comment by HackFisher** [comment]
not reproducable

**Comment by J-mate** [comment]
It still happened on My Mac when I was building version 0.6.1.
