### ISSUE TITLE
balance is 0, but transaction history is there.

### ISSUE THREAD

**Issue by HackFisher** [bitsuperlab/bitshares_play#54]

**Comment by AlexChien** [comment]
Using the latest master branch to build, resync-blockchain and rebuild-index, the problem goes away.  Balance is correct again.

**Comment by HackFisher** [comment]
I did not upgrade the testnet nodes yet.

**Comment by AlexChien** [comment]
Yes, the issue is not solved.  I check it later, balance is gonna again.  I guess early when I see balance is because the wallet is still in he progress of scanning.  When it reaches the problematic TX of voting, the balance is gone.

Alex Chien

**Comment by HackFisher** [comment]
too old
