### ISSUE TITLE
Change the app icon for qt installer app

### ISSUE THREAD

**Issue by HackFisher** [bitsuperlab/bitshares_play#56]

**Comment by HackFisher** [comment]
@AlexChien I just sent the ai logo files to @cassiopaia too, so this issue can keep going on after the images ready, the only thing left is the replace them.

**Comment by cassiopaia** [comment]
cassiopaia@riseup.net

**Comment by AlexChien** [comment]
@cassiopaia sent to your email address, thanks.

**Comment by HackFisher** [comment]
Alex's progress on this: https://github.com/bitsuperlab/qt_play/commit/92b94ba342874c31349eeadc0c30d8d0bda1be7d

But the bitshares.icns is not right

**Comment by AlexChien** [comment]
replaced with updated icons  bitsuperlab/qt_play@46f7c4b7f60e3f63aa2adf42f634be98b4ff6ca4
