### ISSUE TITLE
[web_wallet]  Failed to lineman build

### ISSUE THREAD

**Issue by HackFisher** [bitsuperlab/bitshares_play#57]
```
>> Tasks directory "tasks" not found.

Running "clean:dist" (clean) task

Running "clean:bower" (clean) task

Running "common" task

Running "bower:install" (bower) task
Fatal error: Unable to find suitable version for angular
```

npm WARN package.json bitshares-play-gui@0.0.1 No repository field.
npm WARN prefer global lineman@0.34.2 should be installed with -g

**Comment by HackFisher** [comment]
Gona to ok after update angular resolution to "~1.3.x"

**Comment by HackFisher** [comment]
TODO: update the document

**Comment by AlexChien** [comment]
I will try to build a fresh wallet tomorrow and reproduce this.

**Comment by HackFisher** [comment]
@AlexChien I've fixed this, will give a commit in seconds
