### ISSUE TITLE
[web_wallet] Enable Faucet for testing

### ISSUE THREAD

**Issue by HackFisher** [bitsuperlab/bitshares_play#64]

**Comment by AlexChien** [comment]
progress:

faucet.dacplay.org is live and functioning, social media checklist
[x] Facebook
[x] Twitter
[x] LinkedIn
[x] Google
[x] Github
[x] Reddit
[] Weibo
[] QQ
[] Douban

Un-checked social medias are waiting for approval.

**Comment by HackFisher** [comment]
@AlexChien Please close this if the channels already supported.
