### ISSUE TITLE
[qt wallet] qtapp.ico is not in 3.00 format 

### ISSUE THREAD

**Issue by clar** [bitsuperlab/bitshares_play#71]
Windows build qt wallet： 

1>F:\repo\bitshares_play_0.0.2_build_3\programs\qt_wallet\resource.rc(54): error RC2175: resource file qtapp.ico is not in 3.00 format

Replace with old bts icon, this error will be gone.

**Comment by cassiopaia** [comment]
ok so what we'll need now!?

**Comment by HackFisher** [comment]
@cassiopaia , It's about this file https://github.com/bitsuperlab/qt_play/blob/master/images/qtapp.ico, we need a icon in 3.00 format according to clar.

**Comment by AlexChien** [comment]
@clar please confirm if this icon is OK.  Close issue for now.

**Comment by clar** [comment]
the new icon is ok now.
