### ISSUE TITLE
Require different fees for account names with different length

### ISSUE THREAD

**Issue by HackFisher** [bitsuperlab/bitshares_play#80]
And considering to remove the names in genesis from keyhotee, remove them all.

**Comment by AlexChien** [comment]
Like the idea, should learn lessons from BitShares past experiences.

**Comment by HackFisher** [comment]
Reserve the names which could be a valid public keys, e.g. started with PLS, 
PLS6R3WSRTxxEtZVTFKBnvQ8GttPYquev7DWKKjro9agS5S9TnR2h

**Comment by HackFisher** [comment]
https://github.com/bitsuperlab/bitshares_play/commit/649fbe017361317f3ef2bca79da23d0586031049
