### ISSUE TITLE
[qt wallet] Left navigation bar is missing on windows client

### ISSUE THREAD

**Issue by clar** [bitsuperlab/bitshares_play#81]
![0 0 3](https://cloud.githubusercontent.com/assets/917300/6125339/fade4d9c-b14f-11e4-83cd-35e7517eaa39.png)

**Comment by HackFisher** [comment]
If it is open in browser, everything is normal

**Comment by clar** [comment]
Everything is ok in IE/chrome.
![0 0 3-open-in-ie](https://cloud.githubusercontent.com/assets/917300/6125710/15940ace-b154-11e4-9b06-f07b58113af5.png)

**Comment by HackFisher** [comment]
If right click reload, Then it shows up
