### ISSUE TITLE
[web_wallet] accounts for dry run 3 gui is not showing up

### ISSUE THREAD

**Issue by HackFisher** [bitsuperlab/bitshares_play#87]

**Comment by HackFisher** [comment]
This commit might related:
https://github.com/BitShares/bitshares/commit/12c27a1da3529aff30ab1e935ddaae7764fd74b1#diff-465d87b32b11682583d9acca38ec50eeR358

is_my_account was removed.

**Comment by clar** [comment]
I can see the accounts on mac version,
but on windows they are missing

**Comment by clar** [comment]
seems I didn't get the latest webwallet codes, let me rebuild it

**Comment by HackFisher** [comment]
https://github.com/BitShares/web_wallet/issues/637#issuecomment-77273084
